USE [DESAFIO_MARLIN]
GO

/****** Object:  Table [dbo].[TB_ALUNO]    Script Date: 01/05/2023 20:25:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_ALUNO](
	[ALN_ID] [int] IDENTITY(1,1) NOT NULL,
	[ALN_CPF] [nvarchar](max) NULL,
	[ALN_EMAIL] [nvarchar](max) NULL,
	[ALN_NOME] [nvarchar](max) NULL,
 CONSTRAINT [PK_TB_ALUNO] PRIMARY KEY CLUSTERED 
(
	[ALN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


