USE [DESAFIO_MARLIN]
GO

/****** Object:  Table [dbo].[TB_ALUNO_TURMA]    Script Date: 01/05/2023 20:28:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_ALUNO_TURMA](
	[ALT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ALN_ID] [int] NOT NULL,
	[TRM_ID] [int] NOT NULL,
 CONSTRAINT [PK_TB_ALUNO_TURMA] PRIMARY KEY CLUSTERED 
(
	[ALT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_ALUNO_TURMA]  WITH CHECK ADD  CONSTRAINT [FK_TB_ALUNO_TURMA_TB_ALUNO_ALN_ID] FOREIGN KEY([ALN_ID])
REFERENCES [dbo].[TB_ALUNO] ([ALN_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_ALUNO_TURMA] CHECK CONSTRAINT [FK_TB_ALUNO_TURMA_TB_ALUNO_ALN_ID]
GO

ALTER TABLE [dbo].[TB_ALUNO_TURMA]  WITH CHECK ADD  CONSTRAINT [FK_TB_ALUNO_TURMA_TB_TURMA_TRM_ID] FOREIGN KEY([TRM_ID])
REFERENCES [dbo].[TB_TURMA] ([TRM_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_ALUNO_TURMA] CHECK CONSTRAINT [FK_TB_ALUNO_TURMA_TB_TURMA_TRM_ID]
GO


