USE [DESAFIO_MARLIN]
GO

/****** Object:  Table [dbo].[TB_TURMA]    Script Date: 01/05/2023 20:29:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TURMA](
	[TRM_ID] [int] IDENTITY(1,1) NOT NULL,
	[TRM_NUMERO] [int] NOT NULL,
	[TRM_ANO_LETIVO] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_TB_TURMA] PRIMARY KEY CLUSTERED 
(
	[TRM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


